/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_uta_tcp_jni_KeyboardUtil */

#ifndef _Included_org_uta_tcp_jni_KeyboardUtil
#define _Included_org_uta_tcp_jni_KeyboardUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_uta_tcp_jni_KeyboardUtil
 * Method:    getKeyboardState
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_org_uta_tcp_jni_KeyboardUtil_getKeyboardState
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
